### ISSUE TITLE
Several Technical Issues Present

### ISSUE THREAD

**Issue by katherineMOFADJS** [Roblox/material-update-beta#2]
Aside from problems on the artistic side such as forced colour tinting and loss of material ambiguity, there are several technical errors present as well.

The materials use all kinds of resolutions. Most of them use proper 1k-looking or even 2k-looking textures, but CorrodedMetal uses some 360p obviously-scaled-up mess that looks like it came from a game made in 2008.

Textures don't map properly on non-cuboidal surfaces. Plastic on spheres creates weird lines, definitely not intended.

Several materials either glitch or don't show up at all on lower graphics settings. On the off-hand, studs for some reason map correctly on lower graphics settings but only show up as a fuzzy, stretched texture on higher settings.

Bricks and wood planks don't tile correctly, creating weird transparent lines at their seams. I checked the texture files themselves and this is present in the _middle_ of the image, not at the edge, meaning this could have easily been avoided if the design team knew what they were doing with this

Wood grain texture is very choppy. When viewed under a light, the different "levels" of wood seem far too high of a step. (Don't know how to word this one, but you'll probably know what I'm talking about if you look at it)

This build of the update seems very unfinished and was definitely not fit for release, and that doesn't even count the things that _were_ probably intended and just suck by opinion to most people on the DevForum thread.

I hope whoever decided that this garbage was ready to be uploaded to GitHub learns to pay more attention to the quality of what they're publicizing, because this is completely unacceptable. I'd expect a multimillion company like Roblox to have higher standards than this.

**Comment by gsckoco** [comment]
I am unsure if English is your first language, however seeing as you managed to write 8 paragraphs in perfect English I shall assume that you do speak English well.

Are you stupid dumb or stupid? What part of beta do you not understand? Don't delude yourself, this is in no way the final product.

**Comment by katherineMOFADJS** [comment]
honestly yeah you're right

i sounded unnecessarily bitter in this i regret writing it
